version: '3'
services:
    s3:
        image: minio/minio
        ports:
            - "9000:9000"
        environment:
            - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
            - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
        entrypoint: sh
        command: -c 'mkdir -p /export/testbucket && /usr/bin/minio server /export'
    pg:
        build: ./docker/pg
        env_file:
            - ./docker/pg/walg_env.env
        depends_on:
            - s3
