[[constraint]]
  name = "github.com/DataDog/zstd"
  version = "1.3.4"

[[constraint]]
  name = "github.com/ulikunitz/xz"
  version = "0.5.4"

[[constraint]]
  name = "golang.org/x/crypto"
  source = "https://github.com/golang/crypto"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "golang.org/x/time"

[[constraint]]
  name = "github.com/go-yaml/yaml"
  version = "2.2.1"
[[constraint]]
  name = "github.com/google/brotli"
  version = "1.0.5"
